name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Run Tests
        run: npm test
      
      - name: Deploy to AWS Elastic Beanstalk
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Deploying to AWS Elastic Beanstalk..."
          zip -r application.zip .
          aws elasticbeanstalk create-application-version \
            --application-name YourAppName \
            --version-label v1.0.0-${{ github.sha }} \
            --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_REGION }}-your-app-bucket",S3Key="application.zip"

          aws elasticbeanstalk update-environment \
            --environment-name YourEnvironmentName \
            --version-label v1.0.0-${{ github.sha }}